### ISSUE TITLE
Ensure financial information about all purchases can be logged in Pegasys and is trackable in the TTS Training and Travel Tracker

### ISSUE THREAD

**Issue by ethanheppner** [18F/tts-micropurchase-bots#1]
- [x] Transfer columns not needed on form response sheet to Pegasys sheet
- [x] Set up accounting code VLOOKUP (or equivalent script) for budgets
- [x] Set up script to copy values from the form response sheet to Pegasys sheet
- [x] Ensure script doesn't rewrite values that have already been added to Pegasys sheet if further edits are made to form responses
- [x] Update PDF report script to be responsive to Pegasys sheet instead of form response sheet
- [x] Once all features are working, make updates to live sheet and script
- [x] Set up UI Path bot and test entry of logs
- [x] Once tests are successful, transfer previous purchases and test those
- [x] Once all previous purchases are successfully logged, connect Pegasys sheet with Acq SSoT so all charges are reported in the Training and Travel Tracker.
- [x] Once all is settled with the live EventBot, set up script the same way for the Micropurchase bot
